_target_: src.models.kitti_module.KITTIModule

lr: 0.001,
momentum: 0.9,
bins: 2,
w: 0.4,
alpha: 0.6,

backbone:
  _target_: src.models.components.kitti_net.RegressorNet
  backbone: torchvision.models.resnet18(pretrained=True)
  bins: 2